name: RP
author: Kronoxx and Matdan
version: 1.0
api-version: 1.16
main: ca.kronoxx.RP.Main
commands:
  job:
    description: Permet de changer de metier
    permission: job.use
  health:
      description: Permet de changer la vie global d'un joueur
      permission: health.use
  alert:
    description: Permet de report un bug
  rumor:
    description: Permet de modifier les rumeures
    permission: rumor.use
  admin:
    description: Permet de se mettre en mode Admin
    permission: admin.use

